name: Build and test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache ComputeCpp
        id: cache-computecpp
        uses: actions/cache@v1
        with:
          path: computecpp
          key: 1.2.0-linux

      - name: Setup ComputeCpp
        if: steps.cache-computecpp.outputs.cache-hit != 'true'
        run: |
          mkdir ${GITHUB_WORKSPACE}/computecpp
          wget --no-verbose --no-check-certificate https://computecpp.codeplay.com/downloads/computecpp-ce/1.2.0/ubuntu-16.04-64bit.tar.gz
          tar xf ubuntu-16.04-64bit.tar.gz -C ${GITHUB_WORKSPACE}/computecpp --strip-components=1

      - name: Setup OpenCL headers
        uses: actions/checkout@v2
        with:
          repository: KhronosGroup/OpenCL-Headers
          path: opencl_headers

      - name: Cache OpenCL
        id: cache-opencl
        uses: actions/cache@v1
        with:
          path: opencl
          key: 18.1.0.015-linux

      - name: Setup OpenCL
        if: steps.cache-opencl.outputs.cache-hit != 'true'
        run: |
          mkdir ${GITHUB_WORKSPACE}/opencl-tmp ${GITHUB_WORKSPACE}/opencl
          wget --no-verbose http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
          tar xf l_opencl_p_18.1.0.015.tgz -C ${GITHUB_WORKSPACE}/opencl-tmp --strip-components=1
          7z x ${GITHUB_WORKSPACE}/opencl-tmp/rpm/intel-openclrt-18.1.0.015-18.1.0-015.x86_64.rpm -o${GITHUB_WORKSPACE}/opencl-tmp
          ls ${GITHUB_WORKSPACE}/opencl-tmp/
          7z x ${GITHUB_WORKSPACE}/opencl-tmp/intel-openclrt-18.1.0.015-18.1.0-015.x86_64.cpio -o${GITHUB_WORKSPACE}/opencl-tmp
          mv ${GITHUB_WORKSPACE}/opencl-tmp/opt/intel/opencl_compilers_and_libraries_18.1.0.015/linux/compiler/lib/intel64_lin/* ${GITHUB_WORKSPACE}/opencl
          pushd ${GITHUB_WORKSPACE}/opencl
          rm libOpenCL.so libOpenCL.so.1 libtbb.so libtbbmalloc.so
          ln -s libOpenCL.so.2.0 libOpenCL.so.1
          ln -s libOpenCL.so.2.0 libOpenCL.so
          ln -s libtbb.so.2 libtbb.so
          ln -s libtbbmalloc.so.2 libtbbmalloc.so
          popd

      - name: Configure
        run: |
          mkdir ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          export LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/opencl
          cmake .. -DComputeCpp_DIR=${GITHUB_WORKSPACE}/computecpp -DOpenCL_INCLUDE_DIR=${GITHUB_WORKSPACE}/opencl_headers -DOpenCL_LIBRARY=${GITHUB_WORKSPACE}/opencl/libintelocl.so -DSNN_BUILD_DOCUMENTATION=OFF

      - name: Build
        run: |
          make -j3

      - name: Test
        run: ctest --output-on-failure


